name: FirstPipeline
on:
  push:
    branches:
      - main

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run eslint
      - name: Test
        run: npm test
      - name: Test e2e
        uses: cypress-io/github-action@v6 
        with:
          command: npm run test:e2e
          start: npm run start-test
          wait-on: http://localhost:5000